### ISSUE TITLE
Status: Checking CMDR 

### ISSUE THREAD

**Issue by six-shooter** [seldonlabs/OmniScanner#2]
It seems that in the EDMC gui, the status: checking takes a long while, and then goes to status: ready. but nothing is showing in the box. I've tried with quite a bunch of commanders already. Are there any servers down?

**Comment by seldonlabs** [comment]
Response time is influenced by Inara and ROA latency/traffic, sometimes it could take a few seconds. Servers are ok. Check EDMC's error log at: `%TMP%\EDMarketConnector.log` for errors.

**Comment by six-shooter** [comment]
here's the log:

```
E:D Market Connector 3.0.6.0 2018-06-30T22:41:19
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
plugin DiscordPresence disabled
loading plugin DistanceCalc from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\DistanceCalc\load.py"
loading plugin edmc-bearing from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\edmc-bearing\load.py"
bearing started
loading plugin edmc-chatviewer-master from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\edmc-chatviewer-master\load.py"
Chat Viewer started
loading plugin EDMC-USS-Survey from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py"
loading plugin EDSM-RSE from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\EDSM-RSE\load.py"
plugin ExTool-EDMC-Plugin-master disabled
loading plugin huttonhelper from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\huttonhelper\load.py"
Hutton Helper Started
loading plugin img from load 3 from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\img from load 3\load.py"
Traceback (most recent call last):
  File "plug.pyo", line 181, in load_plugins
  File "plug.pyo", line 83, in __init__
IOError: [Errno 2] No such file or directory: u'C:\\Users\\jorns\\AppData\\Local\\EDMarketConnector\\plugins\\img from load 3\\load.py'
loading plugin OmniScanner from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py"
OmniScanner: 0.4.0 is the latest version
OmniScanner: version 0.4.0 loaded!
loading plugin src from "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\src\load.py"
Traceback (most recent call last):
  File "plug.pyo", line 181, in load_plugins
  File "plug.pyo", line 83, in __init__
IOError: [Errno 2] No such file or directory: u'C:\\Users\\jorns\\AppData\\Local\\EDMarketConnector\\plugins\\src\\load.py'
Traceback (most recent call last):
  File "plug.pyo", line 109, in get_app
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 81, in plugin_app
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 276, in init_gui
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
[USS Survey] Initiating USS Select
[USS Survey] Initiating Cannon Report
[USS Survey] Initiating USS Detector
[USS Survey] Initiating Hyperdiction Detector
[USS Survey] Initiating Patrol
[USS Survey] Initiating News
[USS Survey] Initiating Merope Log
bearing loaded
Chat Viewer loaded
OmniScanner: [WARNING] Error: cannot find key "Nemesis90" in log!
OmniScanner: [WARNING] Error: cannot find key "punter1985" in log!
OmniScanner: [WARNING] Error: cannot find key "Memzi" in log!
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 899, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 1000, in statistics
KeyError: 'TG_ENCOUNTER_IMPRINT'
OmniScanner: Looking for CMDR Besugo
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Unknown Source
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Unknown Source
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Besugo
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Besugo
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Unknown Source
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Unknown Source
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Unknown Source
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
OmniScanner: Looking for CMDR Besugo
Traceback (most recent call last):
  File "plug.pyo", line 293, in notify_journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\load.py", line 241, in journal_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 287, in update_log
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 295, in _show_latest_entry
  File "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\gui.py", line 195, in set_output
AttributeError: 'module' object has no attribute 'parse_reply_for_gui'
2018-06-30T20:51:04Z CMDR SIX-SHOOTER has docked at Jameson Memorial in the Shinrarta Dezhra system 
Got new data (174272 chars)
2018-06-30T20:51:48Z CMDR SIX-SHOOTER has sold 87354 credits of exploration data 
OmniScanner: shutting down
```

**Comment by seldonlabs** [comment]
Should be fixed by this commit: https://github.com/seldonlabs/OmniScanner/commit/af5e445983f5bc1de8c1af906551d0e42e777427

**Comment by seldonlabs** [comment]
Also, send me a list of the plugins you were using in EDMC.

**Comment by six-shooter** [comment]
my plugins are:
HuttonHelper
DistanceCalc
EDSM-RSE
OmniScanner
EDMC-USS-Survey
edmc-bearing
edmc-chatviewer
